name = "Experiments"
uuid = "12345678-1234-5678-9abc-123456789abc"
authors = ["Marco Hidalgo and contributors"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
BayesBase = "b4ee3484-f114-42fe-b91c-797d54a0c67e"
CSTParser = "00ebfdb7-1f24-5e51-bd34-a7502290713f"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
CpuId = "adafc99b-e345-5852-983c-f28acb93d879"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ExponentialFamily = "62312e5e-252a-4322-ace9-a5f4bf9b357b"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
GraphPPL = "b3f8163a-e979-4e85-b43e-1f63d8c8b42c"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReactiveMP = "a194aa59-28ba-4574-a09c-4a745416d6e3"
RxInfer = "86711068-29c9-4ff7-b620-ae75d7495b3d"
SampledSignals = "bd7594eb-a658-542f-9e75-4c4d8908c167"
SignalAnalysis = "df1fea92-c066-49dd-8b36-eace3378ea47"
StaticLint = "b3cc710f-9c33-5bdb-a03d-a94903873e97"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
WAV = "8149f6b0-98f6-5db9-b78f-408fbbb8ef88"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
ArgParse = "1.2.0"
BayesBase = "1.5.8"
CSTParser = "3.4.3"
CSV = "0.10"
CategoricalArrays = "1.0.1"
CpuId = "0.3.1"
DSP = "0.7, 0.8"
DataFrames = "1.6"
DataStructures = "0.18.22"
Dates = "1.11.0"
Distributions = "0.25.120"
ExponentialFamily = "2.1.2"
FFTW = "1.7"
FileIO = "1.16"
Glob = "1.3.1"
GraphPPL = "4.6.5"
JSON3 = "1.14"
LinearAlgebra = "1"
Logging = "1.11.0"
PlotlyJS = "0.18.17"
Plots = "1.40.19"
ProgressMeter = "1.7"
PyCall = "1.96.4"
Random = "1.11.0"
ReactiveMP = "4.6.5, 5"
RxInfer = "4.4.3"
SampledSignals = "2.1.4"
SignalAnalysis = "0.10.4"
StaticLint = "8.2.2"
Statistics = "1.11.1"
StatsFuns = "1.5.0"
TOML = "1.0"
WAV = "1.2"
YAML = "0.4.14"
julia = "1.11"

[extras]
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
CpuId = "adafc99b-e345-5852-983c-f28acb93d879"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
ReTestItems = "817f1d60-ba6b-4fd5-9520-3cf149f6a823"
RxInfer = "86711068-29c9-4ff7-b620-ae75d7495b3d"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ReTestItems", "CpuId", "Coverage", "JuliaFormatter", "RxInfer"]
